{
  "formatVersion": "1.1",
  "component": {
    "url": "../../eupidcredential/3.1.1-SNAPSHOT/eupidcredential-3.1.1-SNAPSHOT.module",
    "group": "at.asitplus.wallet",
    "module": "eupidcredential",
    "version": "3.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "eupidcredential-iosArm64Main-3.1.1-SNAPSHOT.klib",
          "url": "eupidcredential-iosarm64-3.1.1-SNAPSHOT.klib",
          "size": 103332,
          "sha512": "8bceda589381e47579e2623f99374db1177ecf6813c4aaf2c971e1fbd9352b8497c30a42f73021dfcad547d47697516df11fa4cebaaf0d313fa1cdfdd2d9b912",
          "sha256": "406945f00d914450e00a1b2ace2689a86badd038441618aecb8de854025cdaeb",
          "sha1": "d3d05f7f6599de0e5e6af6dfa9993c33420ec883",
          "md5": "7bea581402ede1bbedb3069511855be1"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "eupidcredential-iosarm64-3.1.1-SNAPSHOT-sources.jar",
          "url": "eupidcredential-iosarm64-3.1.1-SNAPSHOT-sources.jar",
          "size": 14655,
          "sha512": "c5ae985766566dfe2e2879cb97021e429abc6afb5b52166999b1618b3c49536b4bc43b18f2ac1f76c33a262835b7f2d53fa0253530d6f1a1171ba1dae68ab37c",
          "sha256": "851b15e28ad406eab13bb95a4c35211eac1b41bbbf5af5f83a4d0ad9246fa2e5",
          "sha1": "3839db161aa95cefeb7565e717f25481836ae89a",
          "md5": "9977248439f3ca1d88eeb55ee09296bb"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "eupidcredential-iosarm64-3.1.1-SNAPSHOT-metadata.jar",
          "url": "eupidcredential-iosarm64-3.1.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0f18604f9cb58e4fd271b1bba806ea19972b5f125446946cd94186058eb3723da4b2c4850fda492aee4a82b992d7824efc001974b73acbcdd7a5c0640c3ad564",
          "sha256": "5266faefbe5e21bd2ee63ac73bd1c9e194e2df5084fbb8eda62ed792138d84ac",
          "sha1": "2ffd9012a4a02467ac359a2ad93f9b2e385afeed",
          "md5": "2c772fd9e758ab399afadeb99778f4aa"
        }
      ]
    }
  ]
}
