{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.wallet",
    "module": "eupidcredential-versionCatalog",
    "version": "3.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "eupidcredential-versionCatalog-3.1.1-SNAPSHOT.toml",
          "url": "eupidcredential-versionCatalog-3.1.1-SNAPSHOT.toml",
          "size": 656,
          "sha512": "f2ef2969d7c7173b202416f5b2e21d818482fd7561002eb8567f7f36b79031d3f19d7d3ecf8ecfb0327280fdfc6b4fbbbccf4b2a432b4031389d6fd8038f54f3",
          "sha256": "326c3e1c13bdfaae9ef4c7a3478643b0a50f0a6efc95286ec5b329768f1b1062",
          "sha1": "15412a528663369f34e45f89f56ec705e0e4e9d6",
          "md5": "7d5733c9ec934ee73898a973c51216e6"
        }
      ]
    }
  ]
}
