{
  "formatVersion": "1.1",
  "component": {
    "url": "../../eupidcredential/3.1.1-SNAPSHOT/eupidcredential-3.1.1-SNAPSHOT.module",
    "group": "at.asitplus.wallet",
    "module": "eupidcredential",
    "version": "3.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "eupidcredential-iosX64Main-3.1.1-SNAPSHOT.klib",
          "url": "eupidcredential-iosx64-3.1.1-SNAPSHOT.klib",
          "size": 103319,
          "sha512": "77cce72b1a4a1af5831b42202cede001ffc5f721309e5399288bd1ec29c5191979fce2561d398af058b23396eb2dc98adddd2c2bcfdafd4970ac2138bd004066",
          "sha256": "bb1be086b8b5892926bc22ae73167631c63950088aafff735358be949e491f02",
          "sha1": "8de2aa1f17d95f82060430e1602a996e26975061",
          "md5": "963117d7a202053112583d1ef825f90c"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "eupidcredential-iosx64-3.1.1-SNAPSHOT-sources.jar",
          "url": "eupidcredential-iosx64-3.1.1-SNAPSHOT-sources.jar",
          "size": 14655,
          "sha512": "c5ae985766566dfe2e2879cb97021e429abc6afb5b52166999b1618b3c49536b4bc43b18f2ac1f76c33a262835b7f2d53fa0253530d6f1a1171ba1dae68ab37c",
          "sha256": "851b15e28ad406eab13bb95a4c35211eac1b41bbbf5af5f83a4d0ad9246fa2e5",
          "sha1": "3839db161aa95cefeb7565e717f25481836ae89a",
          "md5": "9977248439f3ca1d88eeb55ee09296bb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "eupidcredential-iosx64-3.1.1-SNAPSHOT-metadata.jar",
          "url": "eupidcredential-iosx64-3.1.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a4b353d12963ffe3ba346ba1adbe40fe4274fe639e1ed7b61103d6a2e06c2b0789321ab1cc9e651793803290970ca5ba7e62aef326263bfecd6f5fbb4ac03549",
          "sha256": "e6d9efe8da2eb4c24866ce5f34ebeb2d9c5d9f6b521705700bd26d4149c75e36",
          "sha1": "5c681646e44808e98664734702beffb30d991629",
          "md5": "37db024eecf7134cc3397ec9b83dad79"
        }
      ]
    }
  ]
}
