package at.asitplus.openid.jwtpayload.claims

import at.asitplus.signum.indispensable.josef.ConfirmationClaim
import at.asitplus.signum.indispensable.josef.JwtPayload
import kotlin.time.Instant

/**
 * Defined in [draft-ietf-oauth-attestation-based-client-auth](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-attestation-based-client-auth-10)
 * Section 4
 *
 * A JSON Web Token (JWT) generated by the
 * Client Attester that attests to the authenticity of a Client
 * Instance and is cryptographically bound to a key managed by that
 * Client Instance.  A Client Attestation JWT may additionally convey
 * information about the integrity or state of the Client Instance.
 *
 * Not to be confused with the related proofs of possession [ClientAttestationPopClaims]
 */
interface ClientAttestationClaims: JwtPayload, ProofOfPossessionClaims {
    override val subject: String
    override val expiration: Instant
    override val confirmationClaim: ConfirmationClaim
}