{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.wallet",
    "module": "mobiledrivinglicence-versionCatalog",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "mobiledrivinglicence-versionCatalog-1.2.1-SNAPSHOT.toml",
          "url": "mobiledrivinglicence-versionCatalog-1.2.1-SNAPSHOT.toml",
          "size": 510,
          "sha512": "669a7a0b4e5d9844c389a743871294c4ca897e97fc4ca81ab153c142d310b96d89784c5cac557a3e12ce49cfbec26927e8c85f99d95e848cee18c574d9257830",
          "sha256": "90fa648eb3f249967dd2aadbd536bb22d0534fb6620edb0c76870c8772f1d60b",
          "sha1": "d0a257e5ce5007171e049dce6c1a21d30a57ead1",
          "md5": "1bbfea94410139a290558cc600e9f5a6"
        }
      ]
    }
  ]
}
