{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.wallet",
    "module": "eupidcredential",
    "version": "3.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "eupidcredential-metadata-3.1.1-SNAPSHOT.jar",
          "url": "eupidcredential-3.1.1-SNAPSHOT.jar",
          "size": 11017,
          "sha512": "daefe4143d14835805a8e39ca87947378116581aad97236b3615ba18762110387959cb0d102850b8446a7b9f413830e0200c302cde3c36a2950a13af1c018286",
          "sha256": "a21ba4fba3c14661d10b57ac691c62623fb35655077fbbc9224e0185dadc6d5a",
          "sha1": "26bbf9fc1438a398b08a07d60786a17a37a761bd",
          "md5": "e4d3912689aac1f9d584eff976098cb1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "eupidcredential-kotlin-3.1.1-SNAPSHOT-sources.jar",
          "url": "eupidcredential-3.1.1-SNAPSHOT-sources.jar",
          "size": 14655,
          "sha512": "c5ae985766566dfe2e2879cb97021e429abc6afb5b52166999b1618b3c49536b4bc43b18f2ac1f76c33a262835b7f2d53fa0253530d6f1a1171ba1dae68ab37c",
          "sha256": "851b15e28ad406eab13bb95a4c35211eac1b41bbbf5af5f83a4d0ad9246fa2e5",
          "sha1": "3839db161aa95cefeb7565e717f25481836ae89a",
          "md5": "9977248439f3ca1d88eeb55ee09296bb"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iosarm64/3.1.1-SNAPSHOT/eupidcredential-iosarm64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iosarm64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iosarm64/3.1.1-SNAPSHOT/eupidcredential-iosarm64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iosarm64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iosarm64/3.1.1-SNAPSHOT/eupidcredential-iosarm64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iosarm64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iossimulatorarm64/3.1.1-SNAPSHOT/eupidcredential-iossimulatorarm64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iossimulatorarm64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iossimulatorarm64/3.1.1-SNAPSHOT/eupidcredential-iossimulatorarm64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iossimulatorarm64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iossimulatorarm64/3.1.1-SNAPSHOT/eupidcredential-iossimulatorarm64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iossimulatorarm64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iosx64/3.1.1-SNAPSHOT/eupidcredential-iosx64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iosx64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iosx64/3.1.1-SNAPSHOT/eupidcredential-iosx64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iosx64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../eupidcredential-iosx64/3.1.1-SNAPSHOT/eupidcredential-iosx64-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-iosx64",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../eupidcredential-jvm/3.1.1-SNAPSHOT/eupidcredential-jvm-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-jvm",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../eupidcredential-jvm/3.1.1-SNAPSHOT/eupidcredential-jvm-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-jvm",
        "version": "3.1.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../eupidcredential-jvm/3.1.1-SNAPSHOT/eupidcredential-jvm-3.1.1-SNAPSHOT.module",
        "group": "at.asitplus.wallet",
        "module": "eupidcredential-jvm",
        "version": "3.1.1-SNAPSHOT"
      }
    }
  ]
}
