{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobiledrivinglicence/1.2.1-SNAPSHOT/mobiledrivinglicence-1.2.1-SNAPSHOT.module",
    "group": "at.asitplus.wallet",
    "module": "mobiledrivinglicence",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-iosX64Main-1.2.1-SNAPSHOT.klib",
          "url": "mobiledrivinglicence-iosx64-1.2.1-SNAPSHOT.klib",
          "size": 84789,
          "sha512": "5f41acb29193700020ff95cffb9167c705623f55608111c2021b36e9ce021d566a9a333fc1caef4f2dc11213f920a760b08e83bb4d5422501ae909110725c5ba",
          "sha256": "c87dc95f0122c63f943dc21892246a16375edfefe092d71fbc79e89761f5ac73",
          "sha1": "f4bd8f353f7eda6bafd4f30b7719a9c8eec64320",
          "md5": "b434066accc325be2242a5568e9369c6"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mobiledrivinglicence-iosx64-1.2.1-SNAPSHOT-sources.jar",
          "url": "mobiledrivinglicence-iosx64-1.2.1-SNAPSHOT-sources.jar",
          "size": 11163,
          "sha512": "79120c38efc111b77b1bb07e0cf7632f0237995604d324372666ce6d753447d77f4993ea6fedb1aac901bb7386d22a47e78db8a6c682ae8828acbf56a497d4f6",
          "sha256": "7d31851ad96b916916081394ff0468efc19a1b0a5ac95b4034fa47dce75600cf",
          "sha1": "a18ddf800361478224bf3b6d358fa24456916452",
          "md5": "ff0cc85d812c26118f46cec57ffcfd70"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-iosx64-1.2.1-SNAPSHOT-metadata.jar",
          "url": "mobiledrivinglicence-iosx64-1.2.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "775f35630141f2ab356d2b2edbc33f2644488c44eba71af73a08d777172768bf84e7943029a16f7a80ba6641ef777ed404ecb76408f0fdaf9d7553e49429aee4",
          "sha256": "be9bdac968e50723b00d076645a0f93579f97f515aefa68226f93f3f057129f3",
          "sha1": "47beb241ced52cab5d0e57a3c58038242b1a5a3c",
          "md5": "43cb7fc714c7a6877ffba1e5e43bfb81"
        }
      ]
    }
  ]
}
