{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobiledrivinglicence/1.2.1-SNAPSHOT/mobiledrivinglicence-1.2.1-SNAPSHOT.module",
    "group": "at.asitplus.wallet",
    "module": "mobiledrivinglicence",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-iosArm64Main-1.2.1-SNAPSHOT.klib",
          "url": "mobiledrivinglicence-iosarm64-1.2.1-SNAPSHOT.klib",
          "size": 84802,
          "sha512": "543711929a4cc04b8df287b6c363e9c6c3a270500ff568f7f50f2aae758884da4ce1f7b2e82d2f2c5bd1c5acc50e2992ce90897c847846c8ae99d089cbe3a9e3",
          "sha256": "a08b8af557ca838fd6136236f99c6cdeeb836e1390e2e4307218e1b5b9731e16",
          "sha1": "7df2c9e4d8d3272ce20dbe5c5e392185b373098c",
          "md5": "f818b53441962ff332dc60f2a470fa83"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mobiledrivinglicence-iosarm64-1.2.1-SNAPSHOT-sources.jar",
          "url": "mobiledrivinglicence-iosarm64-1.2.1-SNAPSHOT-sources.jar",
          "size": 11163,
          "sha512": "79120c38efc111b77b1bb07e0cf7632f0237995604d324372666ce6d753447d77f4993ea6fedb1aac901bb7386d22a47e78db8a6c682ae8828acbf56a497d4f6",
          "sha256": "7d31851ad96b916916081394ff0468efc19a1b0a5ac95b4034fa47dce75600cf",
          "sha1": "a18ddf800361478224bf3b6d358fa24456916452",
          "md5": "ff0cc85d812c26118f46cec57ffcfd70"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-iosarm64-1.2.1-SNAPSHOT-metadata.jar",
          "url": "mobiledrivinglicence-iosarm64-1.2.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4a91fea6b78ea0437ac576d8f4e7f04e33acf4ad9823d3fd39da8b09874f0872d6001f6a8ca791c6d768b1429b1823cce8315db68989553c7e02e9dbd81158b8",
          "sha256": "64777d44a4cf1d83cecbd5e116e84d50aa54111974c2026858f1de335597c907",
          "sha1": "8fcc1012c56dba281f0d41d1c37ae2a6d29c2fd1",
          "md5": "77fe60958c05a92e3ec11b33d52a774d"
        }
      ]
    }
  ]
}
