{
  "formatVersion": "1.1",
  "component": {
    "url": "../../eupidcredential/3.1.1-SNAPSHOT/eupidcredential-3.1.1-SNAPSHOT.module",
    "group": "at.asitplus.wallet",
    "module": "eupidcredential",
    "version": "3.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "eupidcredential-jvm-3.1.1-SNAPSHOT.jar",
          "url": "eupidcredential-jvm-3.1.1-SNAPSHOT.jar",
          "size": 75174,
          "sha512": "6246186341a5c12467b74f202b2b9b96f0e23339f3002556553699ecc19b39ef972d299823e141be850173163ba1abf9783c8436f7830f34bd7475cfd5279813",
          "sha256": "14d6e3bdf9d81b0de8fbc4b3612ab3d0330f4e96d261c9f045d9305671e378a3",
          "sha1": "9389a3860d3f50e14415bc5eac3ac4f16087eafa",
          "md5": "20f5992d3ad36126fbb4d3720ca245fb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "eupidcredential-jvm-3.1.1-SNAPSHOT.jar",
          "url": "eupidcredential-jvm-3.1.1-SNAPSHOT.jar",
          "size": 75174,
          "sha512": "6246186341a5c12467b74f202b2b9b96f0e23339f3002556553699ecc19b39ef972d299823e141be850173163ba1abf9783c8436f7830f34bd7475cfd5279813",
          "sha256": "14d6e3bdf9d81b0de8fbc4b3612ab3d0330f4e96d261c9f045d9305671e378a3",
          "sha1": "9389a3860d3f50e14415bc5eac3ac4f16087eafa",
          "md5": "20f5992d3ad36126fbb4d3720ca245fb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "eupidcredential-jvm-3.1.1-SNAPSHOT-sources.jar",
          "url": "eupidcredential-jvm-3.1.1-SNAPSHOT-sources.jar",
          "size": 14655,
          "sha512": "c5ae985766566dfe2e2879cb97021e429abc6afb5b52166999b1618b3c49536b4bc43b18f2ac1f76c33a262835b7f2d53fa0253530d6f1a1171ba1dae68ab37c",
          "sha256": "851b15e28ad406eab13bb95a4c35211eac1b41bbbf5af5f83a4d0ad9246fa2e5",
          "sha1": "3839db161aa95cefeb7565e717f25481836ae89a",
          "md5": "9977248439f3ca1d88eeb55ee09296bb"
        }
      ]
    }
  ]
}
