package at.asitplus.wallet.lib.oidvci

import at.asitplus.wallet.lib.DefaultNonceService
import at.asitplus.wallet.lib.NonceService
import kotlin.jvm.JvmOverloads

/**
 * Provides generation and single-use validation of short-lived codes, e.g. authorization codes,
 * pre-authorized codes, or `issuer_state` values.
 *
 * Every kind of code needs its own instance, so that a value valid for one purpose can not be presented for
 * another one: [at.asitplus.wallet.lib.oauth2.SimpleAuthorizationService] keeps one instance per kind.
 *
 * Can be implemented to provide replication across different instances of the enclosing application.
 */
interface CodeService {

    /** Implementers: Generate a new random string, store it for later verification. */
    suspend fun provideCode(): String

    /** Implementers: Verify the value has been generated by this instance, and remove it, i.e. codes are single-use. */
    suspend fun verifyAndRemove(it: String): Boolean

}

/**
 * Holds valid codes in memory, delegating to [nonceService], i.e. entries are protected with a mutex and
 * expire after the lifetime of that service.
 *
 * [RFC 6749 4.1.2](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2) requires authorization codes
 * to be short-lived and single-use.
 */
class DefaultCodeService @JvmOverloads constructor(
    private val nonceService: NonceService = DefaultNonceService(),
) : CodeService {

    override suspend fun provideCode(): String =
        nonceService.provideNonce()

    override suspend fun verifyAndRemove(it: String): Boolean =
        nonceService.verifyAndRemoveNonce(it)
}
