{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobiledrivinglicence/1.2.1-SNAPSHOT/mobiledrivinglicence-1.2.1-SNAPSHOT.module",
    "group": "at.asitplus.wallet",
    "module": "mobiledrivinglicence",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-iosSimulatorArm64Main-1.2.1-SNAPSHOT.klib",
          "url": "mobiledrivinglicence-iossimulatorarm64-1.2.1-SNAPSHOT.klib",
          "size": 84868,
          "sha512": "b39353a1ecadd30663b29554e28a8b1088681c28e3a8d1700ac9dcaa0ea0958a30b5c3dbba48642340a63397f6e6f06a076580d42f65fc4fecc14a979294310b",
          "sha256": "f26b401693074af2b85f2d694550eb8ae7e9fac8350d084a1fa7943f0089550d",
          "sha1": "a2b9d3a8cad57fb2b188e57a01ea399069ecb7e1",
          "md5": "795398280c9d8a2e95a074db7a8c4e96"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mobiledrivinglicence-iossimulatorarm64-1.2.1-SNAPSHOT-sources.jar",
          "url": "mobiledrivinglicence-iossimulatorarm64-1.2.1-SNAPSHOT-sources.jar",
          "size": 11163,
          "sha512": "79120c38efc111b77b1bb07e0cf7632f0237995604d324372666ce6d753447d77f4993ea6fedb1aac901bb7386d22a47e78db8a6c682ae8828acbf56a497d4f6",
          "sha256": "7d31851ad96b916916081394ff0468efc19a1b0a5ac95b4034fa47dce75600cf",
          "sha1": "a18ddf800361478224bf3b6d358fa24456916452",
          "md5": "ff0cc85d812c26118f46cec57ffcfd70"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-iossimulatorarm64-1.2.1-SNAPSHOT-metadata.jar",
          "url": "mobiledrivinglicence-iossimulatorarm64-1.2.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "775f35630141f2ab356d2b2edbc33f2644488c44eba71af73a08d777172768bf84e7943029a16f7a80ba6641ef777ed404ecb76408f0fdaf9d7553e49429aee4",
          "sha256": "be9bdac968e50723b00d076645a0f93579f97f515aefa68226f93f3f057129f3",
          "sha1": "47beb241ced52cab5d0e57a3c58038242b1a5a3c",
          "md5": "43cb7fc714c7a6877ffba1e5e43bfb81"
        }
      ]
    }
  ]
}
