package at.asitplus.rqes

import at.asitplus.rqes.enums.OperationMode
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Deprecated("Renamed", ReplaceWith("SignHashResponseParameters"))
typealias SignHashResponse = SignHashResponseParameters

/**
 * CSC API v2.0.0.2
 * Data class defined in Ch. 11.10
 * Holds response to [SignHashRequestParameters].
 */
@Serializable
data class SignHashResponseParameters(
    /**
     * REQUIRED-CONDITIONAL.
     * One or more Base64-encoded signed hash(es). In case of multiple signatures, the signed
     * hashes SHALL be returned in the same order as the corresponding hashes provided as
     * an input parameter. This value SHALL be returned
     * when [SignHashRequestParameters.operationMode] is not [OperationMode.ASYNCHRONOUS].
     */
    @SerialName("signatures")
    val signatures: List<String>? = null,

    /**
     * REQUIRED-CONDITIONAL.
     * Arbitrary string value generated by the server uniquely identifying the response
     * originated from the server itself. This value SHALL be returned when operationMode is
     * when [SignHashRequestParameters.operationMode] is [OperationMode.ASYNCHRONOUS].
     */
    @SerialName("responseID")
    val responseId: String? = null,
) : QtspSignatureResponse