{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobiledrivinglicence/1.2.1-SNAPSHOT/mobiledrivinglicence-1.2.1-SNAPSHOT.module",
    "group": "at.asitplus.wallet",
    "module": "mobiledrivinglicence",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-jvm-1.2.1-SNAPSHOT.jar",
          "url": "mobiledrivinglicence-jvm-1.2.1-SNAPSHOT.jar",
          "size": 65632,
          "sha512": "bcbb1a05668b9732b400711de7ed6778d5aa3e8069a62946c551377d1fb480a2f386e472baa57677e64dbe6164fc5205b1e7d887a65f8862d37fb1a14199bf59",
          "sha256": "4596a3087218220a580d4f4f2e5f82ab0ae6f38bd670d486c7060e3c8ed79cd4",
          "sha1": "8cbe90162826859ace69d3750490bbbeca2eec29",
          "md5": "14491bef637544fb2c0e90aa85a63621"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.wallet",
          "module": "vck",
          "version": {
            "requires": "5.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobiledrivinglicence-jvm-1.2.1-SNAPSHOT.jar",
          "url": "mobiledrivinglicence-jvm-1.2.1-SNAPSHOT.jar",
          "size": 65632,
          "sha512": "bcbb1a05668b9732b400711de7ed6778d5aa3e8069a62946c551377d1fb480a2f386e472baa57677e64dbe6164fc5205b1e7d887a65f8862d37fb1a14199bf59",
          "sha256": "4596a3087218220a580d4f4f2e5f82ab0ae6f38bd670d486c7060e3c8ed79cd4",
          "sha1": "8cbe90162826859ace69d3750490bbbeca2eec29",
          "md5": "14491bef637544fb2c0e90aa85a63621"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mobiledrivinglicence-jvm-1.2.1-SNAPSHOT-sources.jar",
          "url": "mobiledrivinglicence-jvm-1.2.1-SNAPSHOT-sources.jar",
          "size": 11163,
          "sha512": "79120c38efc111b77b1bb07e0cf7632f0237995604d324372666ce6d753447d77f4993ea6fedb1aac901bb7386d22a47e78db8a6c682ae8828acbf56a497d4f6",
          "sha256": "7d31851ad96b916916081394ff0468efc19a1b0a5ac95b4034fa47dce75600cf",
          "sha1": "a18ddf800361478224bf3b6d358fa24456916452",
          "md5": "ff0cc85d812c26118f46cec57ffcfd70"
        }
      ]
    }
  ]
}
