name: Build JVM artifacts
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar vck
        uses: actions/upload-artifact@v3
        with:
          name: vck
          path: |
            vck/build/libs/*jar
      - name: Upload jar vck-openid
        uses: actions/upload-artifact@v3
        with:
          name: vck-openid
          path: |
            vck-openid/build/libs/*jar
      - name: Upload jar vck-openid-ktor
        uses: actions/upload-artifact@v3
        with:
          name: vck-openid-ktor
          path: |
            vck-openid-ktor/build/libs/*jar
